name: Client Deployment

on:
 push:
  branches: [prod]

permissions:
 id-token: write

jobs:
 deploy-client:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4

   - name: Configure AWS Credentials
     uses: aws-actions/configure-aws-credentials@v4
     with:
      role-to-assume: arn:aws:iam::891084277208:role/deploy-develop
      aws-region: ap-south-1

   - name: Install Dependencies
     working-directory: ./client
     run: npm install

   - name: Build React App
     working-directory: ./client
     run: npm run build

   - name: Deploy static site to S3 bucket
     run: aws s3 sync ./client/dist s3://book-a-call-client.bharatbhusal.com --delete
